#!/usr/bin/env python3
"""
Pack Scripts Test Tool

This script allows testing pack scripts with specified project directory (config files)
and build directory (binary files) without requiring a full compilation.

Usage:
    python3 test_pack_scripts.py -p <project_dir> -b <build_dir> [options]

Example:
    python3 test_pack_scripts.py \\
        -p /path/to/projects/security/xip/config/bk7236n \\
        -b /path/to/build/output \\
        -t parse
"""

import os
import sys
import argparse
import logging
import shutil
import json
import tempfile
from pathlib import Path

# Add parent directory to path to import scripts
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.partitions import Partitions
from scripts.pack_json import PackJson
from scripts.parse_csv import Csv

# Version information
__version__ = '1.0.0'


class PackScriptsTester:
    """Test pack scripts with specified project and build directories"""
    
    def __init__(self, project_dir, build_dir, work_dir=None, debug=False):
        """
        Initialize tester
        
        Args:
            project_dir: Directory containing config files (partitions.csv, pack.json, etc.)
            build_dir: Directory containing binary files (bl2.bin, cpu0_app.bin, etc.)
            work_dir: Working directory for test output (default: test directory)
            debug: Enable debug logging
        """
        self.project_dir = Path(project_dir).resolve()
        self.build_dir = Path(build_dir).resolve()
        
        # Use test directory as base if work_dir not specified
        if work_dir:
            self.work_dir = Path(work_dir).resolve()
        else:
            # Use test directory as base, with script-specific subdirectory
            test_base = Path(__file__).parent
            # Get script name without extension for directory name
            script_name = Path(__file__).stem  # e.g., 'test_pack_scripts'
            self.work_dir = test_base / f'test_output_{script_name}'
        
        self.debug = debug
        
        # Setup logging
        log_level = logging.DEBUG if debug else logging.INFO
        logging.basicConfig(
            level=log_level,
            format='%(levelname)s: %(message)s'
        )
        self.logger = logging.getLogger(__name__)
        
        # Validate directories
        if not self.project_dir.exists():
            raise ValueError(f"Project directory does not exist: {self.project_dir}")
        if not self.build_dir.exists():
            raise ValueError(f"Build directory does not exist: {self.build_dir}")
        
        # Clean and create work directory structure
        self._setup_work_directory_structure()
        
        # Find config files (search in project_dir and subdirectories)
        self.partition_csv = self._find_config_file('partitions.csv')
        self.bin_csv = self._find_config_file('bin.csv')
        self.pack_json = self._find_config_file('pack.json')
        self.nvs_csv = self._find_config_file('nvs.csv')
        self.security_csv = self._find_config_file('security.csv')
        self.ota_csv = self._find_config_file('ota.csv')
        
        # Log found config files
        if self.debug:
            config_files = [
                ('partitions.csv', self.partition_csv),
                ('bin.csv', self.bin_csv),
                ('pack.json', self.pack_json),
                ('nvs.csv', self.nvs_csv),
                ('security.csv', self.security_csv),
                ('ota.csv', self.ota_csv),
            ]
            for name, path in config_files:
                if path.exists():
                    rel_path = path.relative_to(self.project_dir)
                    if rel_path != Path(name):
                        self.logger.debug(f"Found {name} at: {rel_path}")
                    else:
                        self.logger.debug(f"Found {name} in project root")
    
    def _setup_work_directory_structure(self):
        """
        Setup work directory structure and clean old files
        
        Directory structure:
        - inputs/: Configuration files and compiled binary files (input to pack scripts)
        - outputs/: Files generated by pack scripts (output from pack scripts)
            - prebuild/: Files generated by prebuild_process
            - postbuild/: Files generated by postbuild_process
            - generated/: Other generated files
        """
        # Define directory structure
        self.inputs_dir = self.work_dir / 'inputs'  # Config files + compiled binaries
        self.outputs_dir = self.work_dir / 'outputs'  # Pack script generated files
        self.outputs_prebuild_dir = self.outputs_dir / 'prebuild'
        self.outputs_postbuild_dir = self.outputs_dir / 'postbuild'
        self.outputs_generated_dir = self.outputs_dir / 'generated'
        
        # Clean old files if directory exists
        if self.work_dir.exists():
            self.logger.info(f"Cleaning old test files in: {self.work_dir}")
            try:
                shutil.rmtree(self.work_dir)
            except Exception as e:
                self.logger.warning(f"Failed to clean old files: {e}")
        
        # Create directory structure
        self.work_dir.mkdir(parents=True, exist_ok=True)
        self.inputs_dir.mkdir(parents=True, exist_ok=True)
        self.outputs_dir.mkdir(parents=True, exist_ok=True)
        self.outputs_prebuild_dir.mkdir(parents=True, exist_ok=True)
        self.outputs_postbuild_dir.mkdir(parents=True, exist_ok=True)
        self.outputs_generated_dir.mkdir(parents=True, exist_ok=True)
        
        self.logger.info(f"Working directory: {self.work_dir}")
        self.logger.info(f"  Inputs (config files + compiled binaries): {self.inputs_dir}")
        self.logger.info(f"  Outputs (pack script generated files): {self.outputs_dir}")
    
    def _find_config_file(self, filename):
        """
        Find config file in project directory or subdirectories
        
        Args:
            filename: Name of the config file to find
            
        Returns:
            Path object pointing to the file, or Path to non-existent file if not found
        """
        # First, try in project_dir directly
        file_path = self.project_dir / filename
        if file_path.exists():
            return file_path
        
        # Search in common subdirectories
        common_subdirs = [
            'config/bk7236n',
            'config',
            'bk7236n',
        ]
        
        for subdir in common_subdirs:
            file_path = self.project_dir / subdir / filename
            if file_path.exists():
                self.logger.debug(f"Found {filename} in subdirectory: {subdir}")
                return file_path
        
        # If not found, try recursive search (limited depth to avoid performance issues)
        max_depth = 3
        found_files = []
        for path in self.project_dir.rglob(filename):
            relative_path = path.relative_to(self.project_dir)
            depth = len(relative_path.parts) - 1  # Subtract 1 for filename itself
            if depth <= max_depth and depth > 0:
                found_files.append((depth, path, relative_path))
        
        if found_files:
            # Sort by depth (prefer shallower matches)
            found_files.sort(key=lambda x: x[0])
            depth, path, rel_path = found_files[0]
            self.logger.debug(f"Found {filename} at depth {depth}: {rel_path.parent}")
            return path
        
        # Return path even if not found (for error reporting)
        return self.project_dir / filename
    
    def _find_binary_file(self, filename):
        """
        Find binary file in build directory or subdirectories
        
        Args:
            filename: Name of the binary file to find
            
        Returns:
            Path object pointing to the file, or None if not found
        """
        # First, try in build_dir directly
        file_path = self.build_dir / filename
        if file_path.exists():
            return file_path
        
        # Search in common subdirectories
        common_subdirs = [
            'package',
            'package/keys',
            'bk7236n',
            'security',
        ]
        
        for subdir in common_subdirs:
            file_path = self.build_dir / subdir / filename
            if file_path.exists():
                self.logger.debug(f"Found {filename} in build subdirectory: {subdir}")
                return file_path
        
        # If not found, try recursive search (limited depth to avoid performance issues)
        max_depth = 5  # Allow deeper search for build directories
        found_files = []
        for path in self.build_dir.rglob(filename):
            relative_path = path.relative_to(self.build_dir)
            depth = len(relative_path.parts) - 1  # Subtract 1 for filename itself
            if depth <= max_depth and depth > 0:
                found_files.append((depth, path, relative_path))
        
        if found_files:
            # Sort by depth (prefer shallower matches)
            found_files.sort(key=lambda x: x[0])
            depth, path, rel_path = found_files[0]
            self.logger.debug(f"Found {filename} at depth {depth}: {rel_path.parent}")
            return path
        
        # Not found
        return None
    
    def _validate_required_files(self):
        """Validate that required files exist, exit if not found"""
        missing_required = []
        missing_optional = []
        
        # Required config files
        required_configs = [
            ('partitions.csv', self.partition_csv, True),
        ]
        
        # Optional config files
        optional_configs = [
            ('bin.csv', self.bin_csv, False),
            ('pack.json', self.pack_json, False),
            ('nvs.csv', self.nvs_csv, False),
            ('security.csv', self.security_csv, False),
            ('ota.csv', self.ota_csv, False),
        ]
        
        # Check required files
        for name, file_path, is_required in required_configs:
            if not file_path.exists():
                if is_required:
                    missing_required.append((name, file_path))
                else:
                    missing_optional.append((name, file_path))
        
        # Check optional files
        for name, file_path, is_required in optional_configs:
            if not file_path.exists():
                missing_optional.append((name, file_path))
        
        # Exit if required files are missing
        if missing_required:
            self.logger.error("=" * 60)
            self.logger.error("ERROR: Required files not found!")
            self.logger.error("=" * 60)
            for name, file_path in missing_required:
                rel_path = file_path.relative_to(self.project_dir)
                if rel_path != Path(name):
                    self.logger.error(f"  ✗ {name} (searched: {self.project_dir} and subdirectories)")
                else:
                    self.logger.error(f"  ✗ {name} (expected in: {self.project_dir})")
            self.logger.error("")
            self.logger.error("Please ensure the required files exist in the project directory")
            self.logger.error("or its subdirectories (e.g., config/bk7236n/)")
            self.logger.error("=" * 60)
            sys.exit(1)
        
        # Warn about optional files
        if missing_optional:
            for name, file_path in missing_optional:
                rel_path = file_path.relative_to(self.project_dir)
                if rel_path != Path(name):
                    self.logger.warning(f"Optional config file not found: {name} (searched in {self.project_dir} and subdirectories)")
                else:
                    self.logger.warning(f"Optional config file not found: {name}")
    
    def setup_work_dir(self):
        """
        Copy config files and compiled binary files to inputs directory
        
        Inputs directory contains:
        - Configuration files (partitions.csv, pack.json, bin.csv, etc.)
        - Compiled binary files (bl2.bin, cpu0_app.bin, etc.)
        """
        self.logger.info("Setting up inputs directory (config files + compiled binaries)...")
        
        # Validate required files first
        self._validate_required_files()
        
        # Copy config files to inputs directory
        config_files = [
            self.partition_csv,
            self.bin_csv,
            self.pack_json,
            self.nvs_csv,
            self.security_csv,
            self.ota_csv,
        ]
        
        for config_file in config_files:
            if config_file.exists():
                # Copy to inputs directory
                dst = self.inputs_dir / config_file.name
                shutil.copy2(config_file, dst)
                # Log the actual path if it's in a subdirectory
                if config_file.parent != self.project_dir:
                    rel_path = config_file.relative_to(self.project_dir)
                    self.logger.debug(f"Copied config file {config_file.name} from {rel_path} to inputs directory")
                else:
                    self.logger.debug(f"Copied config file {config_file.name} to inputs directory")
        
        # Copy/link compiled binary files to inputs directory
        # Only compiled binaries (from bin.csv) go to inputs directory
        # Pack script generated files (from pack.json outputs) should NOT be in inputs
        
        # Step 1: Get compiled binaries from bin.csv (these are the actual inputs)
        compiled_binaries = []  # From bin.csv - compiled binaries (inputs), must exist
        if self.bin_csv.exists():
            try:
                bin_keys = ['Name', 'Type', 'Partition', 'Version', 'Security_counter']
                csv = Csv(str(self.bin_csv), True, bin_keys)
                for dic in csv.dic_list:
                    bin_name = dic['Name'].strip()
                    compiled_binaries.append(bin_name)
            except Exception as e:
                self.logger.warning(f"Failed to parse bin.csv: {e}")
        
        # Step 2: Get pack script output files and required input files from pack.json
        pack_output_files = set()  # Files generated by pack scripts (outputs)
        pack_required_inputs = set()  # Files required as inputs to pack actions (from pack.json bin arrays)
        if self.pack_json.exists():
            try:
                with open(self.pack_json, 'r') as f:
                    pack_data = json.load(f)
                for output_file, value in pack_data.items():
                    # The key is the output file name (generated by pack script)
                    pack_output_files.add(output_file)
                    # Files listed in 'bin' array are inputs to this pack action
                    if 'bin' in value and isinstance(value['bin'], list):
                        for bin_file in value['bin']:
                            # Only add if it's not a pack output (intermediate files are handled by pack scripts)
                            if bin_file not in pack_output_files:
                                pack_required_inputs.add(bin_file)
            except Exception as e:
                self.logger.warning(f"Failed to parse pack.json: {e}")
        
        # Step 3: Combine all required input binaries
        # - Compiled binaries from bin.csv (primary inputs)
        # - Additional inputs from pack.json that are not pack outputs (like xip_a.bin, user_mfr.bin)
        all_input_binaries = set(compiled_binaries)
        all_input_binaries.update(pack_required_inputs)
        # Remove any that are pack outputs (shouldn't be in inputs)
        input_binaries = [b for b in all_input_binaries if b not in pack_output_files]
        
        self.logger.debug(f"Compiled binaries (inputs): {input_binaries}")
        self.logger.debug(f"Pack script outputs: {sorted(pack_output_files)}")
        
        # Check compiled binaries (inputs) first
        missing_required = []
        existing_required = []
        
        for bin_file in input_binaries:
            # Search for binary file in build directory and subdirectories
            src = self._find_binary_file(bin_file)
            dst = self.inputs_dir / bin_file
            
            if src is not None:
                # Use symlink if possible, otherwise copy
                try:
                    if dst.exists() or dst.is_symlink():
                        dst.unlink()
                    dst.symlink_to(src)
                    # Log the actual path if it's in a subdirectory
                    if src.parent != self.build_dir:
                        rel_path = src.relative_to(self.build_dir)
                        self.logger.debug(f"Created symlink: {bin_file} (from {rel_path})")
                    else:
                        self.logger.debug(f"Created symlink: {bin_file}")
                except (OSError, NotImplementedError):
                    # Fallback to copy if symlink fails (e.g., on Windows)
                    shutil.copy2(src, dst)
                    if src.parent != self.build_dir:
                        rel_path = src.relative_to(self.build_dir)
                        self.logger.debug(f"Copied binary: {bin_file} (from {rel_path})")
                    else:
                        self.logger.debug(f"Copied binary: {bin_file}")
                existing_required.append(bin_file)
            else:
                missing_required.append(bin_file)
        
        # Note: Pack script output files (from pack.json) should NOT be in inputs
        # They will be generated by pack scripts and saved to outputs directory
        if pack_output_files:
            self.logger.info("")
            self.logger.info("Pack script output files (will be generated to outputs/):")
            for bin_file in sorted(pack_output_files):
                self.logger.info(f"  → {bin_file}")
        
        # Exit if required binaries are missing
        if missing_required:
            self.logger.error("=" * 60)
            self.logger.error("ERROR: Required binary files not found in build directory!")
            self.logger.error("=" * 60)
            self.logger.error(f"Build directory: {self.build_dir}")
            self.logger.error("Searched in: root, package/, package/keys/, bk7236n/, security/, and subdirectories (max depth: 5)")
            self.logger.error("")
            self.logger.error("Missing required binary files (from bin.csv):")
            for bin_file in missing_required:
                self.logger.error(f"  ✗ {bin_file}")
            self.logger.error("")
            if existing_required:
                self.logger.info("Found compiled binary files (inputs):")
                for bin_file in existing_required:
                    self.logger.info(f"  ✓ {bin_file}")
            if pack_output_files:
                self.logger.info("")
                self.logger.info("Pack script output files (will be generated to outputs/):")
                for bin_file in sorted(pack_output_files):
                    self.logger.info(f"  → {bin_file}")
            self.logger.error("")
            self.logger.error("Please ensure all required binary files exist in the build directory")
            self.logger.error("or its subdirectories (e.g., package/, package/keys/)")
            self.logger.error("=" * 60)
            sys.exit(1)
        
        # Change to inputs directory (where config files and compiled binaries are)
        # Pack scripts will read from here and generate outputs to outputs_dir
        self.original_cwd = os.getcwd()
        os.chdir(self.inputs_dir)
        self.logger.info(f"Changed to inputs directory: {self.inputs_dir}")
        self.logger.info(f"Pack script outputs will be saved to: {self.outputs_dir}")
    
    def cleanup(self):
        """Cleanup work directory"""
        if hasattr(self, 'original_cwd'):
            os.chdir(self.original_cwd)
        
        # Optionally remove work directory (commented out for debugging)
        # if self.work_dir.exists() and self.work_dir != Path.cwd():
        #     shutil.rmtree(self.work_dir)
        #     self.logger.info(f"Cleaned up work directory: {self.work_dir}")
    
    def test_partition_parse(self):
        """Test partition CSV parsing"""
        self.logger.info("=" * 60)
        self.logger.info("Test 1: Partition CSV Parsing")
        self.logger.info("=" * 60)
        
        partition_csv_path = self.inputs_dir / 'partitions.csv'
        if not partition_csv_path.exists():
            self.logger.error(f"partitions.csv not found: {partition_csv_path}")
            return False
        
        try:
            # Use files from inputs directory
            bin_csv_path = str(self.inputs_dir / 'bin.csv') if (self.inputs_dir / 'bin.csv').exists() else None
            pack_json_path = str(self.inputs_dir / 'pack.json') if (self.inputs_dir / 'pack.json').exists() else None
            
            p = Partitions(
                str(self.partition_csv),
                bin_csv_path,
                pack_json_path
            )
            
            self.logger.info(f"✓ Partition CSV parsed successfully")
            self.logger.info(f"  Total partitions: {len(p._partitions)}")
            
            # Print partition information
            for partition in p._partitions:
                name = partition.name()
                offset = partition.size().offset()
                size = partition.size().size()
                self.logger.info(f"  - {name}: offset=0x{offset:08x} ({offset//1024}KB), size={size//1024}KB")
            
            return True
            
        except Exception as e:
            self.logger.error(f"✗ Partition CSV parsing failed: {e}")
            if self.debug:
                import traceback
                traceback.print_exc()
            return False
    
    def test_partition_validation(self):
        """Test partition validation (duplicates, boundaries, etc.)"""
        self.logger.info("=" * 60)
        self.logger.info("Test 2: Partition Validation")
        self.logger.info("=" * 60)
        
        partition_csv_path = self.inputs_dir / 'partitions.csv'
        if not partition_csv_path.exists():
            self.logger.error(f"partitions.csv not found: {partition_csv_path}")
            return False
        
        try:
            # Use files from inputs directory
            partition_csv_path = str(self.inputs_dir / 'partitions.csv')
            bin_csv_path = str(self.inputs_dir / 'bin.csv') if (self.inputs_dir / 'bin.csv').exists() else None
            pack_json_path = str(self.inputs_dir / 'pack.json') if (self.inputs_dir / 'pack.json').exists() else None
            
            p = Partitions(
                partition_csv_path,
                bin_csv_path,
                pack_json_path
            )
            
            # Validation is done in __init__, so if we get here, validation passed
            self.logger.info("✓ Partition validation passed")
            self.logger.info("  - No duplicate partition names")
            self.logger.info("  - Partition boundaries are correct")
            self.logger.info("  - All bins in bin.csv have corresponding partitions")
            
            return True
            
        except SystemExit as e:
            self.logger.error(f"✗ Partition validation failed (exit code: {e.code})")
            return False
        except Exception as e:
            self.logger.error(f"✗ Partition validation failed: {e}")
            if self.debug:
                import traceback
                traceback.print_exc()
            return False
    
    def test_pack_json_parse(self):
        """Test pack.json parsing"""
        self.logger.info("=" * 60)
        self.logger.info("Test 3: Pack JSON Parsing")
        self.logger.info("=" * 60)
        
        pack_json_path = self.inputs_dir / 'pack.json'
        if not pack_json_path.exists():
            self.logger.warning(f"pack.json not found: {pack_json_path}")
            return True  # Not a failure if file doesn't exist
        
        try:
            # Check JSON format
            with open(pack_json_path, 'r') as f:
                pack_data = json.load(f)
            
            self.logger.info("✓ pack.json JSON format is valid")
            
            # Validate structure
            required_fields = ['bin', 'action']
            valid_actions = [
                'BL1_SIGN', 'BL2_SIGN', 'PACK_BL2_BIN', 'PACK_BL2_DOWNLOAD_BIN',
                'PACK_BL1_DOWNLOAD_BIN', 'PACK_OTA_BIN', 'PACK_RAW_OTA_BIN',
                'PACK_NVS', 'STEPS_PACK_HEADER', 'USER_MFR_AES'
            ]
            
            for key, value in pack_data.items():
                if not isinstance(value, dict):
                    self.logger.error(f"✗ {key}: value must be an object")
                    return False
                
                for field in required_fields:
                    if field not in value:
                        self.logger.error(f"✗ {key}: missing required field '{field}'")
                        return False
                
                action = value.get('action')
                if action not in valid_actions:
                    self.logger.warning(f"⚠ {key}: unknown action '{action}'")
                
                bins = value.get('bin', [])
                if not isinstance(bins, list):
                    self.logger.error(f"✗ {key}: 'bin' must be a list")
                    return False
                
                self.logger.info(f"  - {key}: action={action}, bins={bins}")
            
            self.logger.info("✓ pack.json structure validation passed")
            return True
            
        except json.JSONDecodeError as e:
            self.logger.error(f"✗ pack.json JSON format error: {e}")
            return False
        except Exception as e:
            self.logger.error(f"✗ pack.json parsing failed: {e}")
            if self.debug:
                import traceback
                traceback.print_exc()
            return False
    
    def test_code_generation(self):
        """Test code generation (prebuild_process)"""
        self.logger.info("=" * 60)
        self.logger.info("Test 4: Code Generation")
        self.logger.info("=" * 60)
        
        partition_csv_path = self.inputs_dir / 'partitions.csv'
        if not partition_csv_path.exists():
            self.logger.error(f"partitions.csv not found: {partition_csv_path}")
            return False
        
        try:
            # Use files from inputs directory
            partition_csv_path = str(self.inputs_dir / 'partitions.csv')
            bin_csv_path = str(self.inputs_dir / 'bin.csv') if (self.inputs_dir / 'bin.csv').exists() else None
            pack_json_path = str(self.inputs_dir / 'pack.json') if (self.inputs_dir / 'pack.json').exists() else None
            
            p = Partitions(
                partition_csv_path,
                bin_csv_path,
                pack_json_path
            )
            
            # Run prebuild_process to generate code
            # This generates partitions_gen.h in the current working directory (inputs_dir)
            p.prebuild_process()
            
            # Check if partitions_gen.h was generated (pack script output)
            gen_h_file = Path('partitions_gen.h')
            if gen_h_file.exists():
                self.logger.info("✓ partitions_gen.h generated successfully (pack script output)")
                
                # Move to prebuild output directory (this is a pack script generated file)
                output_file = self.outputs_prebuild_dir / 'partitions_gen.h'
                shutil.move(str(gen_h_file), str(output_file))
                
                # Check file content
                with open(output_file, 'r') as f:
                    content = f.read()
                    if 'BK_FLASH_PARTITIONS_MAP' in content:
                        self.logger.info("  - Partition map macro found")
                    if 'BK_PARTITION_' in content:
                        self.logger.info("  - Partition ID macros found")
                
                self.logger.info(f"  Pack script output saved to: {output_file}")
                return True
            else:
                self.logger.error("✗ partitions_gen.h was not generated")
                return False
                
        except Exception as e:
            self.logger.error(f"✗ Code generation failed: {e}")
            if self.debug:
                import traceback
                traceback.print_exc()
            return False
    
    def test_pack_json_object(self):
        """Test PackJson object creation"""
        self.logger.info("=" * 60)
        self.logger.info("Test 5: PackJson Object Creation")
        self.logger.info("=" * 60)
        
        pack_json_path = self.inputs_dir / 'pack.json'
        if not pack_json_path.exists():
            self.logger.warning(f"pack.json not found: {pack_json_path}")
            return True
        
        try:
            pack = PackJson()
            self.logger.info("✓ PackJson object created successfully")
            
            # Try to create pack objects (this will parse pack.json)
            # We don't actually pack, just test the parsing
            pack._packs = []  # Clear packs list
            pack._PackJson__create_pack(str(pack_json_path))
            
            self.logger.info(f"  Created {len(pack._packs)} pack objects")
            for p in pack._packs:
                self.logger.info(f"  - {p._outfile}: {type(p).__name__}")
            
            return True
            
        except Exception as e:
            self.logger.error(f"✗ PackJson object creation failed: {e}")
            if self.debug:
                import traceback
                traceback.print_exc()
            return False
    
    def test_actual_pack(self):
        """
        Test actual pack process - generate pack script output files
        
        This will actually run the pack scripts to generate output files like
        all-app.bin, bootloader.bin, app_signed.bin, etc.
        """
        self.logger.info("=" * 60)
        self.logger.info("Test 7: Actual Pack Process")
        self.logger.info("=" * 60)
        
        pack_json_path = self.inputs_dir / 'pack.json'
        if not pack_json_path.exists():
            self.logger.warning(f"pack.json not found: {pack_json_path}")
            return True
        
        try:
            # Create PackJson object and run actual pack process
            pack = PackJson()
            
            # Run pack process (may require keys, but we try anyway)
            # Note: This may fail if keys are missing, but that's OK for testing
            try:
                pack.pack(
                    pack_json=str(pack_json_path),
                    img_sign_pubkey=None,
                    img_sign_privkey=None,
                    flash_aes_key=None,
                    flash_crc_en=True,
                    data_aes_key=None
                )
                self.logger.info("✓ Pack process completed")
            except Exception as pack_error:
                self.logger.warning(f"⚠ Pack process encountered errors (may need keys): {pack_error}")
                # Continue to check what files were generated anyway
            
            # Check for generated output files and move them to outputs directory
            pack_output_files = set()
            if pack_json_path.exists():
                try:
                    with open(pack_json_path, 'r') as f:
                        pack_data = json.load(f)
                    for output_file in pack_data.keys():
                        pack_output_files.add(output_file)
                except Exception as e:
                    self.logger.warning(f"Failed to parse pack.json: {e}")
            
            generated_files = []
            missing_files = []
            
            # Check for generated files in current directory (inputs_dir)
            for output_file in pack_output_files:
                file_path = Path(output_file)
                if file_path.exists():
                    # Move to outputs directory
                    if output_file in ['bootloader.bin', 'all-app.bin']:
                        dst = self.outputs_postbuild_dir / output_file
                    else:
                        dst = self.outputs_generated_dir / output_file
                    
                    try:
                        shutil.move(str(file_path), str(dst))
                        generated_files.append(output_file)
                        self.logger.info(f"  ✓ Generated and saved: {output_file} -> {dst.relative_to(self.work_dir)}")
                    except Exception as e:
                        self.logger.warning(f"  ⚠ Failed to move {output_file}: {e}")
                else:
                    missing_files.append(output_file)
            
            if generated_files:
                self.logger.info(f"✓ Generated {len(generated_files)} pack output files:")
                for f in generated_files:
                    self.logger.info(f"  - {f}")
            
            if missing_files:
                self.logger.warning(f"⚠ {len(missing_files)} pack output files not generated (may need keys or dependencies):")
                for f in missing_files:
                    self.logger.warning(f"  - {f}")
            
            # Also check for other generated files (like nvs_key.bin, nvs.bin, partition.bin)
            other_generated = ['nvs_key.bin', 'nvs.bin', 'partition.bin', 'xip_a.bin']
            for gen_file in other_generated:
                file_path = Path(gen_file)
                if file_path.exists():
                    dst = self.outputs_generated_dir / gen_file
                    try:
                        shutil.move(str(file_path), str(dst))
                        self.logger.info(f"  ✓ Found and saved: {gen_file} -> {dst.relative_to(self.work_dir)}")
                    except Exception as e:
                        self.logger.debug(f"  Failed to move {gen_file}: {e}")
            
            # Return True if at least some files were generated, or if it's just missing keys
            return len(generated_files) > 0 or len(missing_files) == len(pack_output_files)
            
        except Exception as e:
            self.logger.error(f"✗ Actual pack process failed: {e}")
            if self.debug:
                import traceback
                traceback.print_exc()
            # Don't fail the test if pack fails (may need keys)
            return True
    
    def test_binary_files_exist(self):
        """
        Test if required compiled binary files exist in inputs directory
        
        Only checks compiled binaries from bin.csv (inputs), not pack script outputs.
        Pack script outputs (from pack.json) should NOT be in inputs directory.
        """
        self.logger.info("=" * 60)
        self.logger.info("Test 6: Compiled Binary Files Check (Inputs)")
        self.logger.info("=" * 60)
        
        # Only check compiled binaries from bin.csv (these are the inputs)
        # Do NOT check pack script outputs (from pack.json)
        compiled_bins = []
        
        bin_csv_path = self.inputs_dir / 'bin.csv'
        if bin_csv_path.exists():
            try:
                bin_keys = ['Name', 'Type', 'Partition', 'Version', 'Security_counter']
                csv = Csv(str(bin_csv_path), True, bin_keys)
                for dic in csv.dic_list:
                    bin_name = dic['Name'].strip()
                    compiled_bins.append(bin_name)
            except Exception as e:
                self.logger.warning(f"Failed to parse bin.csv: {e}")
                return False
        
        if not compiled_bins:
            self.logger.warning("No compiled binaries found in bin.csv")
            return True  # Not a failure if bin.csv is empty
        
        # Get pack script output files to exclude from check
        pack_output_files = set()
        pack_json_path = self.inputs_dir / 'pack.json'
        if pack_json_path.exists():
            try:
                with open(pack_json_path, 'r') as f:
                    pack_data = json.load(f)
                for output_file in pack_data.keys():
                    pack_output_files.add(output_file)
            except Exception as e:
                self.logger.warning(f"Failed to parse pack.json: {e}")
        
        # Filter: only check compiled binaries that are NOT pack script outputs
        input_bins_to_check = [b for b in compiled_bins if b not in pack_output_files]
        
        missing_bins = []
        existing_bins = []
        
        for bin_file in input_bins_to_check:
            bin_path = self.inputs_dir / bin_file
            if bin_path.exists() or bin_path.is_symlink():
                existing_bins.append(bin_file)
            else:
                missing_bins.append(bin_file)
        
        if existing_bins:
            self.logger.info(f"✓ Found {len(existing_bins)} compiled binary files (inputs):")
            for bin_file in existing_bins:
                self.logger.info(f"  - {bin_file}")
        
        if missing_bins:
            self.logger.error(f"✗ Missing {len(missing_bins)} compiled binary files (inputs):")
            for bin_file in missing_bins:
                self.logger.error(f"  - {bin_file}")
            self.logger.error("")
            self.logger.error("These are compiled binaries (inputs) that must exist in build directory.")
            return False
        
        # Note about pack script outputs
        if pack_output_files:
            self.logger.info("")
            self.logger.info("Note: Pack script output files (from pack.json) are NOT checked here.")
            self.logger.info("They will be generated by pack scripts and saved to outputs/ directory:")
            for bin_file in sorted(pack_output_files):
                self.logger.info(f"  → {bin_file}")
        
        return True
    
    def run_tests(self, test_mode='all'):
        """
        Run tests based on test mode
        
        Args:
            test_mode: 'parse', 'validate', 'generate', 'pack', 'all'
        """
        self.logger.info("=" * 60)
        self.logger.info("Pack Scripts Test Suite")
        self.logger.info("=" * 60)
        self.logger.info(f"Project directory: {self.project_dir}")
        self.logger.info(f"Build directory: {self.build_dir}")
        self.logger.info(f"Work directory: {self.work_dir}")
        self.logger.info(f"Test mode: {test_mode}")
        self.logger.info("=" * 60)
        
        # Setup work directory
        try:
            self.setup_work_dir()
        except Exception as e:
            self.logger.error(f"Failed to setup work directory: {e}")
            return False
        
        results = {}
        
        try:
            # Run tests based on mode
            if test_mode in ['parse', 'all']:
                results['partition_parse'] = self.test_partition_parse()
            
            if test_mode in ['validate', 'all']:
                results['partition_validation'] = self.test_partition_validation()
            
            if test_mode in ['parse', 'all']:
                results['pack_json_parse'] = self.test_pack_json_parse()
            
            if test_mode in ['generate', 'all']:
                results['code_generation'] = self.test_code_generation()
            
            if test_mode in ['pack', 'all']:
                results['pack_json_object'] = self.test_pack_json_object()
            
            if test_mode in ['pack', 'all']:
                results['actual_pack'] = self.test_actual_pack()
            
            if test_mode in ['all']:
                results['binary_files'] = self.test_binary_files_exist()
            
            # Print summary
            self.logger.info("=" * 60)
            self.logger.info("Test Summary")
            self.logger.info("=" * 60)
            
            all_passed = True
            for test_name, passed in results.items():
                status = "✓ PASS" if passed else "✗ FAIL"
                self.logger.info(f"{status}: {test_name}")
                if not passed:
                    all_passed = False
            
            self.logger.info("=" * 60)
            if all_passed:
                self.logger.info("All tests passed!")
            else:
                self.logger.warning("Some tests failed. Check logs above for details.")
            
            return all_passed
            
        finally:
            self.cleanup()
        
        return False


def main():
    parser = argparse.ArgumentParser(
        description='Test pack scripts with specified project and build directories',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run all tests
  python3 test_pack_scripts.py \\
      -p /path/to/projects/security/xip/config/bk7236n \\
      -b /path/to/build/output

  # Run only parsing tests
  python3 test_pack_scripts.py \\
      -p /path/to/projects/security/xip/config/bk7236n \\
      -b /path/to/build/output \\
      -t parse

  # Run with debug output
  python3 test_pack_scripts.py \\
      -p /path/to/projects/security/xip/config/bk7236n \\
      -b /path/to/build/output \\
      -d

  # Clear test output directory only
  python3 test_pack_scripts.py --clear

  # Clear and run tests
  python3 test_pack_scripts.py \\
      -c -p /path/to/projects/security/xip/config/bk7236n \\
      -b /path/to/build/output
        """
    )
    
    parser.add_argument(
        '--version',
        action='version',
        version=f'%(prog)s {__version__}'
    )
    
    parser.add_argument(
        '-p', '--project_dir',
        type=str,
        required=False,
        help='Project directory containing config files (partitions.csv, pack.json, etc.). Script will search in subdirectories like config/bk7236n/ if not found in root.'
    )
    
    parser.add_argument(
        '-b', '--build_dir',
        type=str,
        required=False,
        help='Build directory containing binary files (bl2.bin, cpu0_app.bin, etc.)'
    )
    
    parser.add_argument(
        '-w', '--work_dir',
        type=str,
        default=None,
        help='Working directory for test output (default: temporary directory)'
    )
    
    parser.add_argument(
        '-t', '--test-mode',
        type=str,
        choices=['parse', 'validate', 'generate', 'pack', 'all'],
        default='all',
        help='Test mode: parse (parsing only), validate (validation only), generate (code generation), pack (pack objects), all (all tests)'
    )
    
    parser.add_argument(
        '-d', '--debug',
        action='store_true',
        help='Enable debug logging'
    )
    
    parser.add_argument(
        '-c', '--clear',
        action='store_true',
        help='Clear test output directory before running tests (or exit after clearing if no other options)'
    )
    
    args = parser.parse_args()
    
    # Function to clear test output directory
    def clear_test_output():
        """Clear test output directory"""
        test_base = Path(__file__).parent
        script_name = Path(__file__).stem  # e.g., 'test_pack_scripts'
        work_dir = test_base / f'test_output_{script_name}'
        
        if work_dir.exists():
            try:
                logging.basicConfig(
                    level=logging.INFO,
                    format='%(levelname)s: %(message)s'
                )
                logger = logging.getLogger(__name__)
                logger.info(f"Clearing test output directory: {work_dir}")
                shutil.rmtree(work_dir)
                logger.info("✓ Test output directory cleared successfully")
                return True
            except Exception as e:
                logging.error(f"Failed to clear test output directory: {e}")
                return False
        else:
            logging.info(f"Test output directory does not exist: {work_dir}")
            return True
    
    # Handle --clear option
    if args.clear:
        success = clear_test_output()
        # If only --clear is specified (no project_dir or build_dir), exit after clearing
        if not args.project_dir or not args.build_dir:
            sys.exit(0 if success else 1)
        # If --clear is specified with other options, continue to run tests
    
    # Validate required arguments for running tests
    if not args.project_dir or not args.build_dir:
        parser.error("--project_dir (-p) and --build_dir (-b) are required when running tests (unless using --clear only)")
    
    try:
        tester = PackScriptsTester(
            project_dir=args.project_dir,
            build_dir=args.build_dir,
            work_dir=args.work_dir,
            debug=args.debug
        )
        
        success = tester.run_tests(test_mode=args.test_mode)
        sys.exit(0 if success else 1)
        
    except KeyboardInterrupt:
        print("\nTest interrupted by user")
        sys.exit(130)
    except Exception as e:
        logging.error(f"Test failed: {e}")
        if args.debug:
            import traceback
            traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    main()

