#!/usr/bin/env python3

import logging
import os

from .pack import Pack

class PackNvs(Pack):
    def __init__(self, bins=None, outfile=None):
        super().__init__(bins, outfile)

    def pack(self, img_sign_pubkey=None, img_sign_privkey=None, flash_aes_key=None, flash_crc_en=True, data_aes_key=None):
        logging.debug(f'PackNvs({self._outfile}): bins={self._bins}, flash_aes_key={flash_aes_key} data_aes_key={data_aes_key}')
        
        # PackNvs action in pack.json is mainly for verification
        # The actual nvs.bin generation should be done by PartitionNvs.postbuild_process()
        # If bins are specified, check if they exist
        if self._bins:
            for bin_file in self._bins:
                if not os.path.exists(bin_file):
                    logging.warning(f'PackNvs: {bin_file} not exists, it should be generated by PartitionNvs.postbuild_process()')
                else:
                    logging.debug(f'PackNvs: {bin_file} exists')