#!/usr/bin/env python3

import logging
import os

from .pack import Pack
from .common import *

# ========== MODIFICATION START: Add PackUserMfr class to handle USER_MFR_AES action ==========
# This class encrypts user_mfr.bin with nvs_key.bin using mbedtls_aes_xts tool
# Reference: README.md - "encrypt user_mfr.bin with nvs_key.bin"
# Note: nvs_key.bin should be generated by Partition.process_partition_nvs_key() in Partitions.process_nvs()
#       PackUserMfr only uses nvs_key.bin, does not generate it (following OOP principle)
class PackUserMfr(Pack):
    def __init__(self, bins=None, outfile=None):
        super().__init__(bins, outfile)

    def pack(self, img_sign_pubkey=None, img_sign_privkey=None, flash_aes_key=None, flash_crc_en=True, data_aes_key=None):
        logging.debug(f'PackUserMfr({self._outfile}): bins={self._bins}, flash_aes_key={flash_aes_key} data_aes_key={data_aes_key}')
        
        if not self._bins or len(self._bins) == 0:
            logging.error('PackUserMfr: no input bins specified')
            exit(1)
        
        # Expect user_mfr.bin as input
        user_mfr_bin = self._bins[0]
        if not os.path.exists(user_mfr_bin):
            logging.error(f'PackUserMfr: {user_mfr_bin} not exists')
            exit(1)
        
        # ========== MODIFICATION START: Check nvs_key.bin exists (should be generated by process_partition_nvs_key) ==========
        # Reference: nvs_key.bin should be generated by Partition.process_partition_nvs_key() in Partitions.process_nvs()
        # PackUserMfr only uses nvs_key.bin, does not generate it
        nvs_key_bin = 'nvs_key.bin'
        if not os.path.exists(nvs_key_bin):
            logging.error(f'PackUserMfr: {nvs_key_bin} not exists. It should be generated by process_partition_nvs_key() when processing nvs_key partition.')
            logging.error(f'PackUserMfr: Please ensure nvs_key partition is processed before USER_MFR_AES action.')
            exit(1)
        logging.debug(f'PackUserMfr: using {nvs_key_bin} for encryption')
        # ========== MODIFICATION END ==========
        
        # Get NVS encryption tool
        nvs_tool = get_nvs_tool()
        
        # Output encrypted file name
        if self._outfile:
            encrypted_bin = self._outfile
        else:
            # Default output: user_mfr_aes.bin or keep original name
            encrypted_bin = user_mfr_bin.replace('.bin', '_aes.bin')
        
        # Encrypt user_mfr.bin with nvs_key.bin
        # Command format: mbedtls_aes_xts key.bin input.bin output.bin 0
        # 0 = encrypt mode, 1 = decrypt mode
        cmd = f'{nvs_tool} {nvs_key_bin} {user_mfr_bin} {encrypted_bin} 0'
        logging.debug(f'PackUserMfr: encrypt {user_mfr_bin} with {nvs_key_bin}: {cmd}')
        run_cmd_not_check_ret(cmd)
        
        # ========== MODIFICATION START: Add pack header to user_mfr_aes.bin ==========
        # Reference: partition_nvs.py and partition_nvs_key.py - add pack header for PackDownload
        self.__add_pack_header_to_user_mfr_aes(encrypted_bin)
        # ========== MODIFICATION END ==========
        
        logging.info(f'PackUserMfr: encrypted {user_mfr_bin} -> {encrypted_bin}')
    
    def __add_pack_header_to_user_mfr_aes(self, encrypted_bin):
        """Add pack header to user_mfr_aes.bin so it can be parsed by PackDownload"""
        from .pack_header import PackHeader
        from .parse_csv import Csv
        
        if not os.path.exists(encrypted_bin):
            logging.warning(f'PackUserMfr: {encrypted_bin} not exists, cannot add pack header')
            return
        
        # Get user_mfr partition information from partitions.csv
        partition_name = 'user_mfr'
        partition_type = 1  # data type
        partition_subtype = 17  # factory subtype (from partition_type.py)
        partition_offset = 0
        partition_size = 0
        partition_flags = 0
        
        # ========== MODIFICATION START: Parse partition info via Partitions object ==========
        # Prefer object getters (similar to ph.size().offset()) instead of parsing partitions_gen.h.
        # This avoids dependency on current working directory layout.
        if os.path.exists('partitions.csv'):
            try:
                from .partitions import Partitions
                parts = Partitions('partitions.csv', None, None)
                p = parts._find_partition_by_name(partition_name)
                if p is not None:
                    partition_offset = p.size().offset()
                    partition_size = p.size().size()
                    partition_type = p.type().type()
                    partition_subtype = p.type().subtype()
                    partition_flags = p.flags().flags()
                    logging.debug(
                        f'PackUserMfr: resolved partition by Partitions object: '
                        f'offset=0x{partition_offset:x}, size=0x{partition_size:x}, flags=0x{partition_flags:x}'
                    )
                else:
                    logging.warning(f'PackUserMfr: partition {partition_name} not found in partitions.csv, using defaults')
            except Exception as e:
                logging.warning(f'PackUserMfr: failed to resolve partition from partitions.csv: {e}, using defaults')
        # ========== MODIFICATION END ==========
        
        # Create pack header for user_mfr_aes.bin
        ph = PackHeader()
        version = "1.0.0"  # Default version
        hdr_size = 0  # No additional header size
        
        ph.create_header(
            encrypted_bin,
            version,
            partition_name,
            partition_type,
            partition_subtype,
            partition_offset,
            partition_size,
            partition_flags,
            hdr_size
        )
        logging.debug(f'PackUserMfr: added pack header to {encrypted_bin}')
# ========== MODIFICATION END ==========

